version: '3.4'

services:
    collector:
      image: sip-threatfox-collector:latest
      build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - THREATFOX_API_KEY
      command: python3 sip_threatfox_collector.py
      hostname: collector
      container_name: sip-threatfox-collector
      restart: always
      networks:
          - threatfox
      # If you do not want any error_reporting and collection logs available on the host, comment the following out.
      volumes:
          - /opt/SIP-ThreatFox-Collector/collector/error_reporting:/SIP-ThreatFox-Collector/error_reporting
          - /opt/SIP-ThreatFox-Collector/collector/logs:/SIP-ThreatFox-Collector/logs
          - /opt/SIP-ThreatFox-Collector/collector/var:/SIP-ThreatFox-Collector/var
networks:
  threatfox:
